name: Deploy branch
description: Deploys branch in PRs

inputs:
  pr_number:
    description: Pull request number
    required: true

  kubeconfig:
    description: Content of ~/.kubeconfig
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pr_number }}
    - ${{ inputs.kubeconfig }}
